#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend cryptotechcoder
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 648535-web-01 54.157.139.128:80 check
    server 648535-web-02 35.174.213.135	:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
